---
  - name: CentOS 6 pre-req
    yum:
      name: libselinux-python
      state: present
    when: ansible_distribution_major_version == "6"

  - name: Disable NetworkManager
    systemd:
      name: NetworkManager
      state: stopped
      enabled: no
    when: ansible_distribution_major_version == "7"

  - import_tasks: discovery.yml

  - name: Add/Modify network interfaces
    template:
      src: "templates/{{ item.type }}.j2"
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.iface }}"
    with_items:
      - "{{ el_network_interfaces }}"
    notify:
      - restart centos6 networking
      - restart centos7 networking
      - restart centos8 networking      

  - name: Delete unconfigured network interfaces
    file:
      path: "/etc/sysconfig/network-scripts/ifcfg-{{ item }}"
      state: absent
    with_items:
      - "{{ el_network_unconfigured_ifaces }}"
    when: el_network_unconfigured_ifaces.0 is defined
    notify:
      - restart centos6 networking
      - restart centos7 networking
      - restart centos8 networking      
